DROP TABLE IF EXISTS Roles CASCADE;

CREATE TABLE Roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  brand_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  FOREIGN KEY (brand_id) REFERENCES Brand_location(id) ON DELETE CASCADE
);