DROP TABLE IF EXISTS Quetsions CASCADE;

CREATE TABLE Quetsions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  test_id INT NOT NULL,
  recipe_id INT NOT NULL,
  FOREIGN KEY (test_id) REFERENCES Tests(id) ON DELETE CASCADE,
  FOREIGN KEY (recipe_id) REFERENCES Drink_recipe(id) ON DELETE CASCADE
);